---
title: "Assignment Documents"
output: 
  html_document:
   toc: true
   toc_float: true
   theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F, message = F)
```
******

All assignments will be posted to this section approximately 1-2 weeks before the due date listed on the course schedule.  Assignments are to be submitted through Quercus and are graded based on completion.  

Perusall assignments are to be submitted on the Perusall website.  To receive full credit, you are to:

* Read the whole paper.
* Add at least 3 comments.
* Add an upvote to a comment/question from someone else.

Note: Even though some assignments may appear short, they take longer than expected to complete. Please do not leave things until the last minute. 

<br>

## Assignment 1 (Probability) - Due Sept 27, 2022 at 9 am

[Assignment Document](https://drive.google.com/file/d/1d-52W4AZN-YGdi6AV2OzxGWD5J886JcS/view?usp=sharing)

[Assignment Solutions](https://q.utoronto.ca/courses/273117/files)


## Assignment 2 (Random Variables) - Due Oct 11, 2022 at 9 am

[Assignment Document](https://drive.google.com/drive/folders/1O708lq2WE6e_w3F-LM6ePvCkoTlkXUPB?usp=sharing)

[Assignment Solutions](https://q.utoronto.ca/courses/273117/files)

## Assignment 3 (Convergence) - Due Oct 25, 2022 at 9am

[Assignment Document](https://drive.google.com/file/d/1ScLoIVTKGqGElteXGfjic4e268kV1fVT/view?usp=sharing)

*Note*: Questions 4bc, 5, and 7 will be easier to answer after lecture on Oct 18.

[Assignment Solutions](https://q.utoronto.ca/courses/273117/files)

## Final Project Sign-Up - Due Nov 5, 2022 at 9am

Sign-up with one another person for the final project on this [sheet](https://docs.google.com/spreadsheets/d/1LQhUz7_ng45QicVoRSQStZ_LKLacc_KQTr9ZqvsatRk/edit?usp=sharing).  This is worth 3 points of the final project grade.

