---
title: ""
output: 
  html_document:
   toc: true
   toc_float: true
   theme: co
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(warning = F, message = F)
```
<br>


## Week 1
  - Course introduction 
  - Lecture: Review of likelihood inference and asymptotic results 

<br>

## Week 2
  - Lecture: The likelihood family: Profile, marginal, conditional, quasi, empirical, etc. 
  - Discussion
    - Background: [Likelihood Inference](https://utstat.toronto.edu/reid/research/likelihood-final.pdf) by Nancy Reid
    - Application: [PIE: A prior knowledge guided integrated likelihood estimation method for bias reduction in association studies using electronic health records data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7378882/) by Jing Huang et al.

<br>

## Week 3
  - Lecture: Likelihood inference under model misspecification 
  - Discussion
    - Article: [Automated feature selection of predictors in electronic medical records data](https://pubmed.ncbi.nlm.nih.gov/30353541/) by Jessica Gronsbell et al.

<br>

## Week 4
  - Lecture: Penalized likelihood 
  - Discussion on High-dimensional likelihood inference
    - Article: [A modern maximum-likelihood theory for high-dimensional logistic regression](https://www-pnas-org.myaccess.library.utoronto.ca/doi/pdf/10.1073/pnas.1810420116) by Pragya Sur and Emmanuel J. Candès

<br>

## Week 5

- Final Presentations

<br>

## Week 6
- Final Presentations



<!-- https://utstat.toronto.edu/reid/research/Carrasco-R-published.pdf -->


  
  <!-- (1) [You want me to analyze data I don't have? Are you insane?](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4198883/) by Xiao-Li Meng and (2) [Maximum likelihood estimation with missing outcomes: From simplicity to complexity](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6879193/) by Stuart Baker -->
